version: '3.1'

services:
  db:
    container_name: tap_mysql
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=tap_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3307:3306"